import Four from "./aboutExplore/four";
import One from "./aboutExplore/one";
import Three from "./aboutExplore/three";
import Two from "./aboutExplore/two";
import Bot from "./bot";
import Cross from "./cross";
import DropdownIcon from "./dropdownIcon";
import Enquiry from "./enquiry";
import Clock from "./explore/clock";
import Icon360 from "./explore/icon360";
import Register from "./explore/register";
import VideoCall from "./explore/videoCall";
import Hamburger from "./hamburger";
import ImageVector from "./imageVector";
import ImageVectorGray from "./imageVectorGray";
import ImageVectorWhite from "./imageVectorWhite";
import LeftArrow from "./leftArrow";
import Call from "./location/call";
import CarbonTime from "./location/carbonTime";
import Email from "./location/email";
import Location from "./location/location";
import Phone from "./phone";
import Quotes from "./quotes";
import Quotes2 from "./quotes2";
import RightArrow from "./rightArrow";
import RightArrowWhite from "./rightArrowWhite";
import SliderIconLeft from "./sliderIconLeft";
import SliderIconRight from "./sliderIconRight";
import SliderLeftBlack from "./sliderLeftBlack";
import SliderRightBlack from "./sliderRightBlack";
import Fb from "./socialmedia/fb";
import Insta from "./socialmedia/insta";
import Linkedin from "./socialmedia/linkedin";
import Yt from "./socialmedia/yt";
import Upload from "./upload";
export const cross = <Cross />;
export const hamburger = <Hamburger />;
export const rightArrow = <RightArrow />;
export const rightArrowWhite = <RightArrowWhite />;
export const dropdownIcon = <DropdownIcon />;
export const sliderIconLeft = <SliderIconLeft />;
export const sliderIconRight = <SliderIconRight />;
export const sliderLeftBlack = <SliderLeftBlack />;
export const sliderRightBlack = <SliderRightBlack />;
export const leftArrow = <LeftArrow />;
export const imageVector = <ImageVector />;
export const clock = <Clock />;
export const icon360 = <Icon360 />;
export const register = <Register />;
export const videoCall = <VideoCall />;
export const quotes = <Quotes />;
export const quotes2 = <Quotes2 />;
export const imageVectorGray = <ImageVectorGray />;
export const imageVectorWhite = <ImageVectorWhite />;
export const phone = <Phone />;
export const fb = <Fb />;
export const insta = <Insta />;
export const linkedin = <Linkedin />;
export const yt = <Yt />;
export const call = <Call />;
export const carbonTime = <CarbonTime />;
export const email = <Email />;
export const location = <Location />;
export const aboutOne = <One />;
export const aboutTwo = <Two />;
export const aboutThree = <Three />;
export const aboutFour = <Four />;
export const bot = <Bot />;
export const upload = <Upload />;
export const enquiry = <Enquiry />;
